# Generated by Django 2.1.2 on 2019-01-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('userid', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': (('can_add_authuser', 'Can add authuser'), ('can_add_student', 'Can add student'), ('can_add_teacher', 'Can add teacher')),
            },
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('regid', models.CharField(max_length=10)),
                ('email', models.EmailField(default='', max_length=120)),
                ('phone', models.CharField(default='', max_length=16)),
                ('address', models.CharField(default='', max_length=30)),
                ('birthday', models.DateField(default=django.utils.timezone.now)),
                ('bloodgroup', models.CharField(default='', max_length=3)),
                ('gender', models.CharField(default='', max_length=1)),
                ('imgsrc', models.CharField(default='', max_length=100)),
                ('githubid', models.CharField(default='', max_length=20)),
                ('linkedinid', models.CharField(default='', max_length=30)),
                ('batch', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='swe.Batch')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('hid', models.CharField(default='', max_length=5)),
                ('email', models.EmailField(default='', max_length=120)),
                ('position', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=16)),
                ('gender', models.CharField(default='', max_length=1)),
                ('imgsrc', models.CharField(default='', max_length=100)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
