# Generated by Django 2.1.2 on 2019-01-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('regid', models.CharField(max_length=10)),
                ('batch', models.CharField(max_length=4)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=30)),
                ('bloodgroup', models.CharField(max_length=3)),
                ('gender', models.CharField(max_length=1)),
                ('imgsrc', models.CharField(max_length=100)),
                ('githubid', models.CharField(max_length=20)),
                ('linkedinid', models.CharField(max_length=30)),
                ('contentloc', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regid', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=65)),
                ('randhash', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=16)),
                ('gender', models.CharField(max_length=1)),
                ('imgsrc', models.CharField(max_length=100)),
                ('contentloc', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=65)),
                ('hashrand', models.CharField(max_length=40)),
            ],
        ),
    ]
