# Generated by Django 2.1.2 on 2019-01-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='hid',
            field=models.CharField(default='', max_length=9),
            preserve_default=False,
        ),
    ]
