# Generated by Django 2.1.2 on 2019-01-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0002_auto_20190119_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
