# Generated by Django 2.1.2 on 2019-01-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0002_auto_20190116_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='position',
            field=models.CharField(choices=[('Lecturer', 'Lecturer'), ('Assistant Professor', 'Assistant Professor'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=25),
        ),
    ]
