# Generated by Django 2.1.2 on 2019-01-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0002_auto_20190109_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authuser',
            options={},
        ),
    ]
