# Generated by Django 2.1.2 on 2019-01-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0006_auto_20190122_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
