# Generated by Django 2.1.2 on 2019-01-23 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0008_auto_20190122_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endrosements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('Teaching', 'Teaching'), ('Research Interest', 'Research Interest'), ('Education', 'Education'), ('Publications', 'Publications'), ('Award & Recognizations', 'Award & Recognizations'), ('Programming Language', 'Programming Language'), ('Technology', 'Technology')], max_length=40)),
                ('value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=25)),
                ('from_date', models.DateField()),
                ('current', models.BooleanField(default=False)),
                ('to_date', models.DateField()),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='cover',
            field=models.CharField(default='data/cover.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='cover',
            field=models.CharField(default='data/cover.jpg', max_length=100),
        ),
    ]
