# Generated by Django 2.1.2 on 2019-01-23 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swe', '0009_auto_20190123_1845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endrosements',
            new_name='Endrosement',
        ),
    ]
